project_id = "znmzhfdsgdxwwmlvkwpd"

[functions.delete-user]
verify_jwt = false

[functions.create-business]
verify_jwt = false

[functions.public-storefront]
verify_jwt = false

[functions.affiliate-join]
verify_jwt = false

[functions.auto-cerrar-jornadas]
verify_jwt = false

[functions.employee-onboarding]
verify_jwt = false

[functions.bivoo-assistant]
verify_jwt = false

[functions.update-employee-password]
verify_jwt = false

[functions.reset-business-data]
verify_jwt = false

[functions.delete-bivoo-employee]
verify_jwt = false

[functions.og-preview]
verify_jwt = false

[functions.optimize-image]
verify_jwt = false